name: Python CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    # Add step to install dependencies
      # Install dependencies (assuming you have a requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Linting with flake8
    - name: Lint with flake8
      run: |
        pip install flake8
         flake8 bad_code.py

      # Run unit tests with pytest
    - name: Run unit tests
      run: |
        pip install pytest
        pytest test_bad_code.py